# Fork mode so Kamailio binds all listen addresses (with -D it only uses the first one)
[Service]
Type=forking
PIDFile=/run/kamailio/kamailio.pid
RuntimeDirectory=kamailio
RuntimeDirectoryMode=0770
ExecStart=
ExecStart=/usr/sbin/kamailio -P /run/kamailio/kamailio.pid -f /etc/kamailio/kamailio.cfg -m 64 -M 8
