local0.=info    -/var/log/kamailio/kamailio-calls.log
local0.=err     -/var/log/kamailio/kamailio-errors.log
local0.=warn    -/var/log/kamailio/kamailio-errors.log

*.*;auth,authpriv.none,local0.none    -/var/log/syslog